### ISSUE TITLE
Object type <class 'str'> cannot be passed to C code

### ISSUE THREAD

**Issue by neihousaigaai** [Kito0615/NetEaseMusicDownloader#8]
I have run
```
py -3 NetEaseMusic.py -s https://music.163.com/#/song?id=427419305
```
in Windows 10 and get error
```
Object type <class 'str'> cannot be passed to C code
```

**Comment by robonxt** [comment]
Same issue here

EDIT: Fixed the issue. check my fork for the files

**Comment by zwsuo** [comment]
line #111 & #112, update them to below:

**Comment by zwsuo** [comment]
line #111 & #112, update them to below:encryptor = AES.new(key.encode("utf-8"), AES.MODE_CBC, iv.encode("utf-8"))
encrypt_text = encryptor.encrypt(text.encode("utf-8"))

**Comment by zwsuo** [comment]
Line #111 & #112, update them to below will work:



```
encryptor = AES.new(key.encode("utf-8"), AES.MODE_CBC, iv.encode("utf-8"))

encrypt_text = encryptor.encrypt(text.encode("utf-8"))
```
